title: Welcome to Another Techie Blog
author: Mike Lister
email: lister_michael@hotmail.com
description: Me sharing my experiences with anything Terraform, Azure, Powershell and all those other good things.


url: "https://anothertechieblog.co.uk"

lang: en-us

google_analytics: G-W2ZWFNRV31

# social links
social:
  name: Mike Lister
  links:
    - https://github.com/mdlister
    - https://facebook.com/mdlister
    - https://twitter.com/mdlister

# Brand Colors
colors:
  primary: "#77B6EA"
  accent: "#EFBA31"
  light: "#E8EEF2"
  dark: "#37393A"
  mid: "#C7D3DD"

# seo
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sass-converter  # Required for SCSS variables

paginate: 4
paginate_path: "/page:num/"

twitter:
  username: mdlister
  card: summary

# build settings
theme: jekyll-theme-midnight
show_downloads: false

permalink: /:slug/

  # Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: anothertechieblog