title: Welcome to Another Techie Blog
author: Mike Lister
email: lister_michael@hotmail.com
description: Me sharing my experiences with anything Terraform, Azure, Powershell and all those other good things.


url: "https://anothertechieblog.co.uk"

lang: en-us

google_analytics: G-W2ZWFNRV31

# social links
social:
  name: Mike Lister
  links:
    - https://github.com/mdlister
    - https://facebook.com/mdlister
    - https://twitter.com/mdlister


# seo
plugins:
  - jekyll-seo-tag
  
twitter:
  username: mdlister
  card: summary

# build settings
theme: jekyll-theme-midnight
show_downloads: false



  