theme: jekyll-theme-midnight

title: [Welcome to Another Techie Blog]
description: [Me sharing my experiences with Terraform Azure Powershell and all those good things.]

show_downloads: ["false"]
google_analytics: [G-W2ZWFNRV31]